name: Deploy Server on port 3000

on:
  push:
    branches:
      - main
    paths:
      - 'server/**'
      - '.github/workflows/deploy-server.yml'
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Git checkout
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
        role-session-name: deploy-backend-session
        aws-region: ${{secrets.AWS_REGION}}

    - name: Update Release with .env
      run: |
          cd server
          echo "DB_HOST=${{secrets.DB_HOST_DEV}}" > .env
          echo "DB_USER=${{secrets.DB_DEV_USERNAME}}" >> .env
          echo "DB_PASS=${{secrets.DB_DEV_PASSWORD }}" >> .env
          echo "DB_NAME=release_monkey_db" >> .env
          echo "DB_TRUST_CERT=true" >> .env
          
    - name: Build docker image
      run: |
          cd server
          sudo docker build -f Dockerfile -t backend-image .

    - name: Upload artifact to S3
      run: aws s3 cp site.zip s3://${{ secrets.BUCKET_NAME }}/backend/application-${{ github.run_id }}.zip
      working-directory: dev-do-list-server/bin/Release/net8.0/linux-x64

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          role-session-name: deploy-server-session
          aws-region: ${{secrets.AWS_REGION}}

      - name: Deploy to Elastic Beanstalk
        run: |
          aws elasticbeanstalk create-application-version --application-name ${{ secrets.SERVER_APP_NAME }} --version-label ${{ github.run_id }} --source-bundle S3Bucket="${{ secrets.BUCKET_NAME }}",S3Key="backend/application-${{ github.run_id }}.zip"
          aws elasticbeanstalk update-environment --application-name ${{ secrets.SERVER_APP_NAME }} --environment-name ${{ secrets.SERVER_ENV_NAME }} --version-label ${{ github.run_id }}
